FROM rust:1.85-slim AS chef
RUN apt-get update && \
    apt-get install -y pkg-config libssl-dev cmake g++ curl protobuf-compiler && \
    rm -rf /var/lib/apt/lists/* && \
    cargo install cargo-chef --locked
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder
WORKDIR /app
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --recipe-path recipe.json

# Build and prepare tests
COPY . .
RUN cargo test --no-run

# Set the entrypoint to run integration tests
ENTRYPOINT ["cargo", "test", "--test", "integration", "--", "--nocapture"]
